services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js

  valkey-session:
    image: valkey/valkey:latest
    container_name: dgt-valkey-session
    ports:
      - "${VALKEY_SESSION_PORT}:6379"
    volumes:
      - "${VALKEY_SESSION_CONFIG_PATH}:/etc/valkey/valkey.conf"
    command: ["valkey-server", "/etc/valkey/valkey.conf"]

  valkey-cache:
    image: valkey/valkey:latest
    container_name: dgt-valkey-cache
    ports:
      - "${VALKEY_CACHE_PORT}:6379"
    volumes:
      - "${VALKEY_CACHE_CONFIG_PATH}:/etc/valkey/valkey.conf"
    command: ["valkey-server", "/etc/valkey/valkey.conf"]