services:
  postgres:
    image: pgvector/pgvector:pg17
    ports:
      - "5432:5432"
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: dungeondb
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      TZ: Asia/Seoul
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js

  valkey-session:
    image: valkey/valkey:latest
    container_name: dgt-valkey-session
    ports:
      - "${VALKEY_SESSION_PORT}:6379"
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./valkey-session/data:/data
      - "${VALKEY_SESSION_CONFIG_PATH}:/etc/valkey/valkey.conf"
    command: ["valkey-server", "/etc/valkey/valkey.conf"]

  valkey-cache:
    image: valkey/valkey:latest
    container_name: dgt-valkey-cache
    ports:
      - "${VALKEY_CACHE_PORT}:6379"
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./valkey-cache/data:/data
      - "${VALKEY_CACHE_CONFIG_PATH}:/etc/valkey/valkey.conf"
    command: ["valkey-server", "/etc/valkey/valkey.conf"]